"""Generate reader-oriented explanatory figures for the bench-dragon paper.

The figures in this module explain the geometry and algorithmic ideas.  They
complement, rather than replace, the numerical validation figures generated by
the other ``plot_*.py`` scripts.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle, FancyArrowPatch, Polygon, Rectangle


PROJECT = Path(__file__).resolve().parents[1]
FIGURE_DIR = PROJECT / "Paper" / "Figures"
SRC_DIR = PROJECT / "Code" / "src"
sys.path.insert(0, str(SRC_DIR))

from turning_path import build_turning_geometry, path_point  # noqa: E402


ORANGE = "#E69F00"
SKY = "#56B4E9"
GREEN = "#009E73"
BLUE = "#0072B2"
VERMILION = "#D55E00"
PURPLE = "#CC79A7"
BLACK = "#202020"
GRAY = "#777777"
LIGHT_GRAY = "#E6E6E6"


def configure_style() -> None:
    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": [
                "Microsoft YaHei",
                "SimHei",
                "Arial",
                "DejaVu Sans",
            ],
            "font.size": 8.5,
            "axes.titlesize": 9.5,
            "axes.labelsize": 8.5,
            "legend.fontsize": 7.5,
            "xtick.labelsize": 7.5,
            "ytick.labelsize": 7.5,
            "axes.linewidth": 0.8,
            "lines.linewidth": 1.6,
            "figure.dpi": 130,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.05,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def finish(fig: plt.Figure, stem: str) -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIGURE_DIR / f"{stem}.pdf")
    fig.savefig(FIGURE_DIR / f"{stem}.png", dpi=600)
    plt.close(fig)


def panel_title(ax: plt.Axes, letter: str, title: str) -> None:
    ax.set_title(f"({letter}) {title}", loc="left", fontweight="bold", pad=5)


def draw_dimension(
    ax: plt.Axes,
    start: tuple[float, float],
    end: tuple[float, float],
    text: str,
    *,
    color: str = BLACK,
) -> None:
    ax.annotate(
        "",
        xy=end,
        xytext=start,
        arrowprops={
            "arrowstyle": "<->",
            "color": color,
            "linewidth": 0.9,
            "shrinkA": 0,
            "shrinkB": 0,
        },
    )
    ax.text(
        0.5 * (start[0] + end[0]),
        0.5 * (start[1] + end[1]) + 0.08,
        text,
        ha="center",
        va="bottom",
        color=color,
    )


def rotated_rectangle(
    center: tuple[float, float],
    length: float,
    width: float,
    angle: float,
) -> np.ndarray:
    corners = np.array(
        [
            [-length / 2, -width / 2],
            [length / 2, -width / 2],
            [length / 2, width / 2],
            [-length / 2, width / 2],
        ]
    )
    rotation = np.array(
        [[np.cos(angle), -np.sin(angle)], [np.sin(angle), np.cos(angle)]]
    )
    return corners @ rotation.T + np.asarray(center)


def plot_problem_overview() -> None:
    fig, axes = plt.subplots(1, 3, figsize=(7.1, 2.65))

    ax = axes[0]
    panel_title(ax, "a", "一节板凳的真实几何")
    for y, length, hole_distance, name, color in (
        (0.70, 3.41, 2.86, "龙头板", BLUE),
        (-0.55, 2.20, 1.65, "龙身板", GREEN),
    ):
        ax.add_patch(
            Rectangle(
                (-length / 2, y - 0.15),
                length,
                0.30,
                facecolor=color,
                edgecolor=BLACK,
                alpha=0.28,
                linewidth=1.0,
            )
        )
        ax.plot(
            [-hole_distance / 2, hole_distance / 2],
            [y, y],
            "o",
            color=VERMILION,
            markersize=4.5,
        )
        draw_dimension(
            ax,
            (-length / 2, y + 0.28),
            (length / 2, y + 0.28),
            f"{name} {length:.2f} m",
        )
        draw_dimension(
            ax,
            (-hole_distance / 2, y - 0.28),
            (hole_distance / 2, y - 0.28),
            f"孔距 {hole_distance:.2f} m",
            color=VERMILION,
        )
    ax.text(0, -1.18, "统一宽度 0.30 m；每端外伸 0.275 m", ha="center")
    ax.set_xlim(-2.0, 2.0)
    ax.set_ylim(-1.35, 1.35)
    ax.axis("off")

    ax = axes[1]
    panel_title(ax, "b", "从把手递推到整条龙")
    theta = np.linspace(0.25, 2.35 * np.pi, 32)
    radius = 0.25 + 0.14 * theta
    x = radius * np.cos(theta)
    y = radius * np.sin(theta)
    ax.plot(x, y, color=GRAY, linewidth=1.0, zorder=1)
    ax.plot(x, y, "o", color=BLUE, markersize=2.5, zorder=2)
    ax.plot(x[:2], y[:2], color=VERMILION, linewidth=3.0)
    ax.annotate(
        "龙头前把手 $P_0$",
        xy=(x[0], y[0]),
        xytext=(0.25, 1.08),
        arrowprops={"arrowstyle": "->", "color": VERMILION},
        color=VERMILION,
    )
    ax.annotate(
        "沿连接顺序逐点求 $P_1,\\ldots,P_{223}$",
        xy=(x[15], y[15]),
        xytext=(-1.15, -1.18),
        arrowprops={"arrowstyle": "->", "color": BLUE},
        color=BLUE,
        ha="left",
    )
    ax.text(0, -1.42, "224 个把手决定 223 节板凳", ha="center")
    ax.set_aspect("equal")
    ax.set_xlim(-1.45, 1.45)
    ax.set_ylim(-1.55, 1.35)
    ax.axis("off")

    ax = axes[2]
    panel_title(ax, "c", "五问对应同一条运动链")
    theta = np.linspace(0, 5.2 * np.pi, 500)
    radius = 0.28 + 0.055 * theta
    x = radius * np.cos(theta)
    y = radius * np.sin(theta)
    ax.plot(x, y, color=BLUE, linewidth=1.4)
    ax.add_patch(Circle((0, 0), 0.70, fill=False, color=VERMILION, linestyle="--"))
    ax.plot([-0.54, 0, 0.54], [-0.45, 0.58, 0.45], color=GREEN, linewidth=2.2)
    ax.add_patch(
        FancyArrowPatch(
            (x[-65], y[-65]),
            (x[-40], y[-40]),
            arrowstyle="-|>",
            mutation_scale=10,
            color=BLUE,
        )
    )
    ax.text(-1.12, 1.05, "问题 1：位置、速度", color=BLUE)
    ax.text(-1.12, 0.80, "问题 2：首次碰撞", color=VERMILION)
    ax.text(-1.12, 0.55, "问题 3：最小螺距", color=PURPLE)
    ax.text(-1.12, -1.02, "问题 4：双圆弧调头", color=GREEN)
    ax.text(-1.12, -1.27, "问题 5：全队限速", color=ORANGE)
    ax.set_aspect("equal")
    ax.set_xlim(-1.25, 1.25)
    ax.set_ylim(-1.42, 1.35)
    ax.axis("off")

    fig.tight_layout(w_pad=1.2)
    finish(fig, "problem_geometry_overview")


def plot_q1_explainer() -> None:
    fig, axes = plt.subplots(1, 2, figsize=(7.1, 3.0))

    ax = axes[0]
    panel_title(ax, "a", "固定弦长方程为何要选“最近根”")
    b = 0.11
    theta = np.linspace(7.0, 28.0, 1200)
    xy = np.column_stack((b * theta * np.cos(theta), b * theta * np.sin(theta)))
    ax.plot(xy[:, 0], xy[:, 1], color=BLUE)
    k = 430
    p_prev = xy[k]
    distances = np.linalg.norm(xy - p_prev, axis=1)
    d = 1.20
    crossings = np.where(np.diff(np.sign(distances - d)) != 0)[0]
    candidates = [idx for idx in crossings if idx > k + 5]
    ax.add_patch(Circle(p_prev, d, fill=False, color=VERMILION, linestyle="--"))
    ax.plot(*p_prev, "o", color=BLACK, markersize=5)
    ax.text(*(p_prev + np.array([0.10, 0.10])), "$P_{i-1}$")
    if candidates:
        nearest = candidates[0]
        ax.plot(*xy[nearest], "o", color=GREEN, markersize=6)
        ax.annotate(
            "沿链方向的第一个交点\n（采用的最近根）",
            xy=xy[nearest],
            xytext=(-2.7, -1.95),
            arrowprops={"arrowstyle": "->", "color": GREEN},
            color=GREEN,
        )
        for idx in candidates[1:3]:
            ax.plot(*xy[idx], "x", color=PURPLE, markersize=6)
    ax.text(-2.9, 2.25, "$\\|P_i-P_{i-1}\\|=d_i$", color=VERMILION)
    ax.set_aspect("equal")
    ax.set_xlim(-3.1, 3.1)
    ax.set_ylim(-2.35, 2.55)
    ax.axis("off")

    ax = axes[1]
    panel_title(ax, "b", "刚性约束把前一把手速度投影到后一把手")
    p0 = np.array([-1.7, -0.45])
    p1 = np.array([1.55, 0.50])
    chord = p1 - p0
    chord /= np.linalg.norm(chord)
    t0 = np.array([0.38, 0.93])
    t1 = np.array([0.82, 0.57])
    ax.plot([p0[0], p1[0]], [p0[1], p1[1]], color=BLACK, linewidth=2.4)
    ax.plot(*p0, "o", color=BLUE, markersize=6)
    ax.plot(*p1, "o", color=GREEN, markersize=6)
    ax.text(*(p0 + np.array([-0.25, -0.28])), "$P_{i-1}$", color=BLUE)
    ax.text(*(p1 + np.array([0.06, -0.28])), "$P_i$", color=GREEN)
    for p, tangent, color, label in (
        (p0, t0, BLUE, "$v_{i-1}$"),
        (p1, t1, GREEN, "$v_i$"),
    ):
        ax.add_patch(
            FancyArrowPatch(
                p,
                p + 1.25 * tangent,
                arrowstyle="-|>",
                mutation_scale=12,
                color=color,
                linewidth=1.8,
            )
        )
        ax.plot(
            [p[0] - tangent[0], p[0] + tangent[0]],
            [p[1] - tangent[1], p[1] + tangent[1]],
            color=color,
            linestyle=":",
            linewidth=1.0,
        )
        ax.text(*(p + 1.35 * tangent), label, color=color)
    ax.add_patch(
        FancyArrowPatch(
            p0,
            p0 + 1.2 * chord,
            arrowstyle="-|>",
            mutation_scale=10,
            color=VERMILION,
            linestyle="--",
        )
    )
    ax.add_patch(
        FancyArrowPatch(
            p1,
            p1 - 1.2 * chord,
            arrowstyle="-|>",
            mutation_scale=10,
            color=VERMILION,
            linestyle="--",
        )
    )
    ax.text(
        0,
        -1.42,
        "沿板凳轴向的相对速度必须为 0\n"
        "$(P_i-P_{i-1})^T(v_i-v_{i-1})=0$",
        ha="center",
        color=VERMILION,
    )
    ax.set_aspect("equal")
    ax.set_xlim(-2.25, 2.35)
    ax.set_ylim(-1.65, 2.05)
    ax.axis("off")

    fig.tight_layout(w_pad=1.4)
    finish(fig, "q1_fixed_chord_velocity_explainer")


def plot_q2_explainer() -> None:
    fig, axes = plt.subplots(1, 3, figsize=(7.1, 2.65))

    ax = axes[0]
    panel_title(ax, "a", "把手线段不等于板凳实体")
    length = 3.41
    holes = 2.86
    ax.add_patch(
        Rectangle(
            (-length / 2, -0.15),
            length,
            0.30,
            facecolor=SKY,
            edgecolor=BLACK,
            alpha=0.45,
        )
    )
    ax.plot([-holes / 2, holes / 2], [0, 0], "o-", color=BLUE, markersize=5)
    draw_dimension(ax, (-length / 2, 0.32), (length / 2, 0.32), "实际板长")
    draw_dimension(
        ax,
        (-holes / 2, -0.36),
        (holes / 2, -0.36),
        "把手孔距",
        color=BLUE,
    )
    ax.text(-1.56, -0.72, "外伸\n0.275 m", ha="center", color=VERMILION)
    ax.text(1.56, -0.72, "外伸\n0.275 m", ha="center", color=VERMILION)
    ax.text(0, -1.05, "碰撞必须检查有长、有宽的定向矩形", ha="center")
    ax.set_xlim(-1.95, 1.95)
    ax.set_ylim(-1.2, 0.75)
    ax.axis("off")

    ax = axes[1]
    panel_title(ax, "b", "存在分离轴：两板凳安全")
    first = rotated_rectangle((-0.65, 0.2), 2.1, 0.45, 0.28)
    second = rotated_rectangle((0.75, -0.35), 1.8, 0.45, -0.45)
    ax.add_patch(Polygon(first, facecolor=SKY, edgecolor=BLUE, alpha=0.48))
    ax.add_patch(Polygon(second, facecolor=ORANGE, edgecolor=VERMILION, alpha=0.48))
    x_axis = np.array([0.0, 1.0])
    ax.axvline(0.1, color=GREEN, linestyle="--", linewidth=1.2)
    ax.annotate(
        "投影区间有正间隙\n$m>0$",
        xy=(0.1, 0.62),
        xytext=(-1.25, 1.20),
        arrowprops={"arrowstyle": "->", "color": GREEN},
        color=GREEN,
    )
    ax.set_aspect("equal")
    ax.set_xlim(-1.75, 1.75)
    ax.set_ylim(-1.25, 1.45)
    ax.axis("off")

    ax = axes[2]
    panel_title(ax, "c", "四个轴均无法分开：接触或重叠")
    first = rotated_rectangle((-0.45, 0.05), 2.1, 0.45, 0.28)
    second = rotated_rectangle((0.70, -0.15), 1.8, 0.45, -0.45)
    ax.add_patch(Polygon(first, facecolor=SKY, edgecolor=BLUE, alpha=0.48))
    ax.add_patch(Polygon(second, facecolor=ORANGE, edgecolor=VERMILION, alpha=0.48))
    ax.plot([0.0], [0.03], "o", color=VERMILION, markersize=5)
    ax.annotate(
        "首次接触 $m=0$\n继续运动则 $m<0$",
        xy=(0.0, 0.03),
        xytext=(-1.35, 1.18),
        arrowprops={"arrowstyle": "->", "color": VERMILION},
        color=VERMILION,
    )
    ax.set_aspect("equal")
    ax.set_xlim(-1.75, 1.75)
    ax.set_ylim(-1.25, 1.45)
    ax.axis("off")

    fig.tight_layout(w_pad=0.8)
    finish(fig, "q2_sat_geometry_explainer")


def plot_q3_explainer() -> None:
    fig, axes = plt.subplots(1, 2, figsize=(7.1, 3.15))

    ax = axes[0]
    panel_title(ax, "a", "约束作用在“完整盘入路径”，不只在终点")
    theta = np.linspace(7.4, 16.4, 800)
    b = 0.45
    r = b * theta
    x = r * np.cos(theta)
    y = r * np.sin(theta)
    ax.plot(x, y, color=BLUE)
    ax.add_patch(Circle((0, 0), 4.5, fill=False, color=BLACK, linestyle="--"))
    critical_r = 4.572603
    idx = int(np.argmin(np.abs(r - critical_r)))
    ax.plot(x[idx], y[idx], "o", color=VERMILION, markersize=6)
    ax.annotate(
        "途中先达到临界接触\n$r=4.572603$ m",
        xy=(x[idx], y[idx]),
        xytext=(-6.8, 5.45),
        arrowprops={"arrowstyle": "->", "color": VERMILION},
        color=VERMILION,
    )
    end_idx = int(np.argmin(np.abs(r - 4.5)))
    ax.plot(x[end_idx], y[end_idx], "s", color=GREEN, markersize=5)
    ax.annotate(
        "调头边界\n$r=4.5$ m",
        xy=(x[end_idx], y[end_idx]),
        xytext=(2.5, -6.55),
        arrowprops={"arrowstyle": "->", "color": GREEN},
        color=GREEN,
    )
    ax.add_patch(
        FancyArrowPatch(
            (x[220], y[220]),
            (x[250], y[250]),
            arrowstyle="-|>",
            mutation_scale=11,
            color=BLUE,
        )
    )
    ax.set_aspect("equal")
    ax.set_xlim(-7.3, 7.3)
    ax.set_ylim(-7.1, 7.1)
    ax.axis("off")

    ax = axes[1]
    panel_title(ax, "b", "内层找最危险位置，外层找临界螺距")
    p_star = 0.450337393027
    p = np.linspace(p_star - 3.5e-6, p_star + 3.5e-6, 200)
    phi = 0.9981 * (p - p_star)
    ax.plot((p - p_star) * 1e6, phi * 1e6, color=BLUE)
    ax.axhline(0, color=BLACK, linewidth=0.8)
    ax.axvline(0, color=GRAY, linestyle=":")
    ax.scatter(
        [-1, 0, 1],
        1e6 * 0.9981 * np.array([-1e-6, 0, 1e-6]),
        color=[VERMILION, BLACK, GREEN],
        zorder=3,
    )
    ax.fill_between(
        (p - p_star) * 1e6,
        phi * 1e6,
        0,
        where=phi < 0,
        color=VERMILION,
        alpha=0.12,
    )
    ax.fill_between(
        (p - p_star) * 1e6,
        phi * 1e6,
        0,
        where=phi > 0,
        color=GREEN,
        alpha=0.12,
    )
    ax.text(-3.25, -2.65, "不可行：途中重叠", color=VERMILION)
    ax.text(0.65, 2.55, "可行：全程分离", color=GREEN)
    ax.annotate(
        "外层二分锁定 $p^*$",
        xy=(0, 0),
        xytext=(-3.1, 1.3),
        arrowprops={"arrowstyle": "->", "color": PURPLE},
        color=PURPLE,
    )
    ax.text(
        0,
        -3.15,
        "$\\Phi(p)=\\min\\,m$（沿完整盘入路径）\n"
        "每次计算 $\\Phi$ 都先做一次内层连续极小搜索",
        ha="center",
        va="top",
    )
    ax.set_xlabel("$p-p^*$（$10^{-6}$ m）")
    ax.set_ylabel("全路径最小裕量 $\\Phi(p)$（$10^{-6}$ m）")
    ax.set_xlim(-3.5, 3.5)
    ax.set_ylim(-4.0, 3.7)
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(alpha=0.18)

    fig.tight_layout(w_pad=1.5)
    finish(fig, "q3_full_path_search_explainer")


def plot_q4_explainer() -> None:
    geometry = build_turning_geometry()
    fig, axes = plt.subplots(1, 3, figsize=(7.1, 2.95))

    ax = axes[0]
    panel_title(ax, "a", "端点切向决定双圆弧几何")
    s_values = np.linspace(-8, geometry.total_arc_length + 8, 800)
    points = [path_point(float(s), geometry) for s in s_values]
    x = np.array([p.x for p in points])
    y = np.array([p.y for p in points])
    segments = np.array([p.segment for p in points])
    styles = {
        "inward-spiral": (BLUE, "-"),
        "first-arc": (VERMILION, "-"),
        "second-arc": (GREEN, "-"),
        "outward-spiral": (BLUE, "--"),
    }
    for segment, (color, style) in styles.items():
        mask = segments == segment
        ax.plot(x[mask], y[mask], color=color, linestyle=style)
    ax.add_patch(Circle((0, 0), 4.5, fill=False, color=GRAY, linestyle=":"))
    key_points = {
        "A": (geometry.entry_x, geometry.entry_y),
        "J": (geometry.join_x, geometry.join_y),
        "B": (geometry.exit_x, geometry.exit_y),
        "$C_1$": (geometry.first_center_x, geometry.first_center_y),
        "$C_2$": (geometry.second_center_x, geometry.second_center_y),
    }
    for label, point in key_points.items():
        ax.plot(*point, "o", color=BLACK, markersize=3.5)
        ax.text(point[0] + 0.18, point[1] + 0.18, label)
    ax.plot(
        [geometry.first_center_x, geometry.join_x],
        [geometry.first_center_y, geometry.join_y],
        color=VERMILION,
        linestyle=":",
    )
    ax.plot(
        [geometry.second_center_x, geometry.join_x],
        [geometry.second_center_y, geometry.join_y],
        color=GREEN,
        linestyle=":",
    )
    ax.text(-4.35, 4.15, "$R_1=2R_2$", color=PURPLE)
    ax.set_aspect("equal")
    ax.set_xlim(-5.2, 5.2)
    ax.set_ylim(-5.2, 5.2)
    ax.axis("off")

    ax = axes[1]
    panel_title(ax, "b", "一条弧长坐标贯穿四个路径段")
    lengths = [5.0, geometry.first_length, geometry.second_length, 5.0]
    labels = [
        "盘入螺线\n$s<0$",
        "圆弧 1\n$0\\leq s\\leq L_1$",
        "圆弧 2\n$L_1<s\\leq L$",
        "盘出螺线\n$s>L$",
    ]
    colors = [SKY, VERMILION, GREEN, SKY]
    hatches = ["//", "", "", "\\\\"]
    total = sum(lengths)
    left = 0.0
    for length, label, color, hatch in zip(lengths, labels, colors, hatches):
        ax.add_patch(
            Rectangle(
                (left, 0.12),
                length,
                0.55,
                facecolor=color,
                edgecolor=BLACK,
                alpha=0.55,
                hatch=hatch,
            )
        )
        ax.text(
            left + length / 2,
            0.86,
            label,
            ha="center",
            va="bottom",
            fontsize=7.2,
        )
        left += length
    ax.annotate(
        "",
        xy=(total + 0.5, 0.395),
        xytext=(-0.5, 0.395),
        arrowprops={"arrowstyle": "-|>", "color": BLACK},
    )
    ax.text(total / 2, -0.15, "前进方向：$s$ 单调增加", ha="center")
    ax.text(
        total / 2,
        -0.78,
        "$q(s)$ 与 $\\tau(s)$ 在 A、J、B 处连续\n"
        "同一时刻，不同把手可以分处四段",
        ha="center",
        color=PURPLE,
    )
    ax.set_xlim(-0.7, total + 0.7)
    ax.set_ylim(-1.05, 1.60)
    ax.axis("off")

    ax = axes[2]
    panel_title(ax, "c", "跨段把手仍按第一个后向根递推")
    s_prev = geometry.first_length + 1.3
    p_prev = path_point(s_prev, geometry)
    scan_s = np.linspace(-6, s_prev, 1000)
    scan_points = np.array(
        [(path_point(float(s), geometry).x, path_point(float(s), geometry).y)
         for s in scan_s]
    )
    ax.plot(scan_points[:, 0], scan_points[:, 1], color=BLUE)
    ax.plot(p_prev.x, p_prev.y, "o", color=BLACK, markersize=5)
    ax.text(p_prev.x + 0.15, p_prev.y + 0.15, "$P_{i-1}$")
    d = 2.0
    ax.add_patch(Circle((p_prev.x, p_prev.y), d, fill=False,
                        color=VERMILION, linestyle="--"))
    residual = np.linalg.norm(
        scan_points - np.array([p_prev.x, p_prev.y]), axis=1
    ) - d
    crossings = np.where(np.diff(np.sign(residual)) != 0)[0]
    if crossings.size:
        idx = crossings[-1]
        root = scan_points[idx]
        ax.plot(*root, "o", color=GREEN, markersize=6)
        ax.annotate(
            "向后扫描遇到的第一个根\n即 $P_i$",
            xy=root,
            xytext=(-4.9, 3.75),
            arrowprops={"arrowstyle": "->", "color": GREEN},
            color=GREEN,
        )
    ax.add_patch(
        FancyArrowPatch(
            (p_prev.x - 0.2, p_prev.y - 0.2),
            (p_prev.x - 1.4, p_prev.y - 1.4),
            arrowstyle="-|>",
            mutation_scale=11,
            color=PURPLE,
        )
    )
    ax.text(p_prev.x - 2.2, p_prev.y - 1.85, "$s$ 减小：沿链向后搜索", color=PURPLE)
    ax.set_aspect("equal")
    ax.set_xlim(-5.2, 5.2)
    ax.set_ylim(-5.2, 5.2)
    ax.axis("off")

    fig.tight_layout(w_pad=1.0)
    finish(fig, "q4_turning_geometry_explainer")


def main() -> None:
    configure_style()
    plot_problem_overview()
    plot_q1_explainer()
    plot_q2_explainer()
    plot_q3_explainer()
    plot_q4_explainer()
    print("Generated 5 explanatory figures in", FIGURE_DIR)


if __name__ == "__main__":
    main()
